#!/bin/sh

#  procmon postrm
#
#  2016.02.05 john dey
#
set -e
if [ "$1" = "upgrade" -o "$1" = "remove" -o "$1" = "purge" ]; then
    if [ -e /var/run/procmon.pid ]; then
        service procmon stop
    fi
fi

exit 0
