#! /usr/bin/env python3

import os, sys, pwd, csv

def main():
    
    if len(sys.argv) < 3:
        print("Replaces a csv file column containing uidNumbers with real user names !")
        print("usage: %s <csv-file> <column-#-to-replace>" % sys.argv[0])
        return False
    myfile = sys.argv[1]
    column = int(sys.argv[2])
    
    with open(myfile, 'r') as fh:
        reader = csv.reader(fh)
        for line in reader:
            try:               
                user=pwd.getpwuid(int(line[column-1]))[0]
                print(','.join(line).replace(line[column-1], user))

            except:
                print(','.join(line))
            
if __name__=="__main__":
    try:
        main()
    except KeyboardInterrupt:
        print ('Exit !')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
