#! /bin/bash
#  * LF Backup *
#  wrapper for lf-backup.py
#  toolset similar to known unix file system tools for easy
#  interaction with the openstack swift object store 
# 
# 10.24.2016 - bmcgough
#    modified to use Lmod correctly (as root)
#    source old modulefiles as EB Python does not include swictclient
#    avoid bash 'if [ -d $INVALID_ENV_VAR ]' as that returns true


scriptname=${0##*/}
cwd=$(pwd)

. /app/Lmod/lmod/lmod/init/bash
module use /app/Modules/modulefiles

module load python3

./${scriptname}.py $@
